version: "3.9"
services:

  prometheus:
    container_name: ${COMPOSE_PROJECT_NAME}-prometheus
    build:
      context: ${PROMETHEUS_PATH}
    ports:
      - ${PROMETHEUS_PORT}:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ${PROMETHEUS_PATH}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-volume:/prometheus
    depends_on:
      - cadvisor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: ${RESTART_CONTAINERS}

  cadvisor:
    container_name: ${COMPOSE_PROJECT_NAME}-cadvisor
    build:
      context: ${CADVISOR_PATH}
    ports:
      - ${CADVISOR_PORT}:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    privileged: true
    restart: ${RESTART_CONTAINERS}
    
volumes:
  prometheus-volume:

networks:
  default:
    name: cmonitor-net
